baseline:
  name: "baseline"
  data:
    out_format: "png"
    train:
      limit: false
      patchify: true
      augment_before:
      augment_after:
      patch:
        size_x: 128
        size_y: 128
        step: 128
    test:
      limit: false
      patchify: true
      augment_before:
      augment_after:
      patch:
        size_x: 128
        size_y: 128
        step: 128

  unet:
    depth: 4
    pool_factor: 2

  train:
    max_epochs: 50
    learning_rate: 0.0002
    batch_size: 256
    use_validation: true
    validation_size: 0.15  # of trainings data

  test:
    use_best_model: true  # if false load from model_name
    model_name: "best_model-v2.ckpt"

baseline_large_patch:
  name: "baseline_large_patch"
  data:
    out_format: "png"
    train:
      limit: false
      patchify: true
      augment_before:
      augment_after:
      patch:
        size_x: 256
        size_y: 256
        step: 256
    test:
      limit: false
      patchify: true
      augment_before:
      augment_after:
      patch:
        size_x: 256
        size_y: 256
        step: 256

  unet:
    depth: 4
    pool_factor: 4

  train:
    max_epochs: 200
    learning_rate: 0.0005
    batch_size: 256
    use_validation: true
    validation_size: 0.15  # of trainings data
  test:
    use_best_model: true  # if false load from model_name
    model_name: "best_model-v2.ckpt"
