no_augment_default:
  name: "no_augment_default"
  data:
    out_format: "png"
    take_preprocessed: false
    patch:
      use: true
      size_x: 128
      size_y: 128
      step: 128
    train:
      limit: false
      patchify: true
      shrink:
        use: true
        factor: 0.75
      augment_before:
      augment_after:
    test:
      limit: false
      patchify: true
      augment_before:
      augment_after:

  unet:
    depth: 4
    pool_factor: 2

  train:
    max_epochs: 40
    learning_rate: 0.0002
    batch_size: 64
    use_validation: true
    validation_size: 0.15  # of trainings data

  test:
    use_best_model: true  # if false load from model_name
    model_name: "best_model.ckpt"

no_augment_depth_6:
  name: "no_augment_depth_6"
  data:
    out_format: "png"
    take_preprocessed: false
    patch:
      use: true
      size_x: 128
      size_y: 128
      step: 128
    train:
      limit: false
      patchify: true
      shrink:
        use: true
        factor: 0.75
      augment_before:
      augment_after:
    test:
      limit: false
      patchify: true
      augment_before:
      augment_after:

  unet:
    depth: 6
    pool_factor: 2

  train:
    max_epochs: 40
    learning_rate: 0.0002
    batch_size: 64
    use_validation: true
    validation_size: 0.15  # of trainings data

  test:
    use_best_model: true  # if false load from model_name
    model_name: "best_model.ckpt"

no_augment_depth_2:
  name: "no_augment_depth_2"
  data:
    out_format: "png"
    take_preprocessed: false
    patch:
      use: true
      size_x: 128
      size_y: 128
      step: 128
    train:
      limit: false
      patchify: true
      shrink:
        use: true
        factor: 0.75
      augment_before:
      augment_after:
    test:
      limit: false
      patchify: true
      augment_before:
      augment_after:

  unet:
    depth: 2
    pool_factor: 2

  train:
    max_epochs: 40
    learning_rate: 0.0002
    batch_size: 64
    use_validation: true
    validation_size: 0.15  # of trainings data

  test:
    use_best_model: true  # if false load from model_name
    model_name: "best_model.ckpt"

no_augment_size_256:
  name: "no_augment_size_256"
  data:
    out_format: "png"
    take_preprocessed: false
    patch:
      use: true
      size_x: 256
      size_y: 256
      step: 256
    train:
      limit: false
      patchify: true
      shrink:
        use: true
        factor: 0.75
      augment_before:
      augment_after:
    test:
      limit: false
      patchify: true
      augment_before:
      augment_after:

  unet:
    depth: 4
    pool_factor: 2

  train:
    max_epochs: 40
    learning_rate: 0.0002
    batch_size: 32
    use_validation: true
    validation_size: 0.15  # of trainings data

  test:
    use_best_model: true  # if false load from model_name
    model_name: "best_model.ckpt"

no_augment_size_64:
  name: "no_augment_size_64"
  data:
    out_format: "png"
    take_preprocessed: false
    patch:
      use: true
      size_x: 64
      size_y: 64
      step: 64
    train:
      limit: false
      patchify: true
      shrink:
        use: true
        factor: 0.75
      augment_before:
      augment_after:
    test:
      limit: false
      patchify: true
      augment_before:
      augment_after:

  unet:
    depth: 4
    pool_factor: 2

  train:
    max_epochs: 40
    learning_rate: 0.0002
    batch_size: 64
    use_validation: true
    validation_size: 0.15  # of trainings data

  test:
    use_best_model: true  # if false load from model_name
    model_name: "best_model.ckpt"

no_augment_size_256_depth_6:
  name: "no_augment_size_256_depth_6"
  data:
    out_format: "png"
    take_preprocessed: false
    patch:
      use: true
      size_x: 256
      size_y: 256
      step: 256
    train:
      limit: false
      patchify: true
      shrink:
        use: true
        factor: 0.75
      augment_before:
      augment_after:
    test:
      limit: false
      patchify: true
      augment_before:
      augment_after:

  unet:
    depth: 6
    pool_factor: 2

  train:
    max_epochs: 40
    learning_rate: 0.0002
    batch_size: 64
    use_validation: true
    validation_size: 0.15  # of trainings data

  test:
    use_best_model: true  # if false load from model_name
    model_name: "best_model.ckpt"

augment_all:
  name: "augment_all"
  data:
    out_format: "png"
    take_preprocessed: false
    patch:
      use: true
      size_x: 128
      size_y: 128
      step: 128
    train:
      limit: false
      patchify: true
      shrink:
        use: true
        factor: 0.75
      augment_before:
      augment_after:
        augment_random:
          use: true
          num_augmentations: 3
          pick_random: 3
          methods:
            - random_rotation
            - random_horizontal_flip
            - random_vertical_flip
            - gaussian_blur
            - elastic_transform
          color_jitter: true
    test:
      limit: false
      patchify: true
      augment_before:
      augment_after:

  unet:
    depth: 4
    pool_factor: 2

  train:
    max_epochs: 40
    learning_rate: 0.0002
    batch_size: 64
    use_validation: true
    validation_size: 0.15  # of trainings data

  test:
    use_best_model: true  # if false load from model_name
    model_name: "best_model.ckpt"

augment_rotation:
  name: "augment_rotation"
  data:
    out_format: "png"
    take_preprocessed: false
    patch:
      use: true
      size_x: 128
      size_y: 128
      step: 128
    train:
      limit: false
      patchify: true
      shrink:
        use: true
        factor: 0.75
      augment_before:
      augment_after:
        augment_random:
          use: true
          num_augmentations: 1
          pick_random: 1
          methods:
            - random_rotation
          color_jitter: false
    test:
      limit: false
      patchify: true
      augment_before:
      augment_after:

  unet:
    depth: 4
    pool_factor: 2

  train:
    max_epochs: 40
    learning_rate: 0.0002
    batch_size: 64
    use_validation: true
    validation_size: 0.15  # of trainings data

  test:
    use_best_model: true  # if false load from model_name
    model_name: "best_model.ckpt"

augment_flip:
  name: "augment_flip"
  data:
    out_format: "png"
    take_preprocessed: false
    patch:
      use: true
      size_x: 128
      size_y: 128
      step: 128
    train:
      limit: false
      patchify: true
      shrink:
        use: true
        factor: 0.75
      augment_before:
      augment_after:
        augment_random:
          use: true
          num_augmentations: 1
          pick_random: 1
          methods:
            - random_horizontal_flip
            - random_vertical_flip
          color_jitter: false
    test:
      limit: false
      patchify: true
      augment_before:
      augment_after:

  unet:
    depth: 4
    pool_factor: 2

  train:
    max_epochs: 40
    learning_rate: 0.0002
    batch_size: 64
    use_validation: true
    validation_size: 0.15  # of trainings data

  test:
    use_best_model: true  # if false load from model_name
    model_name: "best_model.ckpt"

augment_blur:
  name: "augment_blur"
  data:
    out_format: "png"
    take_preprocessed: false
    patch:
      use: true
      size_x: 128
      size_y: 128
      step: 128
    train:
      limit: false
      patchify: true
      shrink:
        use: true
        factor: 0.75
      augment_before:
      augment_after:
        augment_random:
          use: true
          num_augmentations: 1
          pick_random: 1
          methods:
            - gaussian_blur
          color_jitter: false
    test:
      limit: false
      patchify: true
      augment_before:
      augment_after:

  unet:
    depth: 4
    pool_factor: 2

  train:
    max_epochs: 40
    learning_rate: 0.0002
    batch_size: 64
    use_validation: true
    validation_size: 0.15  # of trainings data

  test:
    use_best_model: true  # if false load from model_name
    model_name: "best_model.ckpt"
