data:
  data_dir: "data/"
  test_data_dir: "data/test/"
  out_format: "png"
  prepare_for: ['train']
  train:
    dir: "train"
    annotations_xml_dir: "Annotations"
    images_tif_dir: "Tissue Images"
    binary_masks: "processed/binary_masks"
    color_masks: "processed/color_masks"
    augment_before:
    augment_after:
      patch:
        size_x: 128
        size_y: 128
        step: 128
        binary_dir: "patch/bin"
        image_dir: "patch/image"
  test:
    dir: "train"
    annotations_xml_dir: "Annotations"
    images_tif_dir: "Tissue Images"
    binary_masks: "processed/binary_masks"
    color_masks: "processed/color_masks"
    augment: []

train:

